### ISSUE TITLE
Imgix WP doesnt replace image URLs specified in the theme php

### ISSUE THREAD

**Issue by jivamatic** [imgix/imgix-wordpress#1]
The plug in works great on images specified directly in the pages. Doesnt work when images are specified in the theme php.

**Comment by jacktasia** [comment]
Hi jivamatic,

Thanks for the report. Do you know if your theme is registering a [filter](https://codex.wordpress.org/Function_Reference/apply_filters)? If you see `apply_filters` references in your theme code then it will probably be easy to update the plugin to ensure those URLs are changed as well.  See [this source code](https://github.com/imgix/imgix-wordpress/blob/master/plugin/includes/do-functions.php#L134). If you're unsure, then if you could point me to your theme I'd be happy to check if we can support it as well. Thanks!

**Comment by jivamatic** [comment]
Thanks Jack. This is a custom theme. If you could point me to an example of a theme modified to support the WP plugin, we could make the same changes in our theme as well.

**Comment by jacktasia** [comment]
Hi jivamatic,

Thanks for the response. As far as I know no themes have been modified to use our WP plugin. If you'd like to share your theme with us (support@imgix.com) then I'd be happy to help integrate your theme with our plugin.

**Comment by austinheap** [comment]
It's true that this plugin does not replace images in your theme. Specifically, it filters the value of "the_content" (what is in the body of the page or post) and "post_thumbnail_html".

To get your theme to support imgix, (I think) you need to buffer your output and add a custom filter for this plugin or modify the PHP/CSS of your theme directly to point at your imgix source. The former is what worked for me.

**Comment by jivamatic** [comment]
I worked around by adding a variable with the CDN path to the theme. Its a hack, but solves the problem for now.
