### ISSUE TITLE
Href's not change

### ISSUE THREAD

**Issue by NonoQ** [imgix/imgix-wordpress#11]
I have a little problem beacuse when i use this plugin, the links on my site doesn't change to imgix url's. :/ i set evrything correctly

**Comment by kellysutton** [comment]
Hi @NonoQ,

Thanks for filing an issue. The imgix-wordpress plugin is only designed to work with the `src` attribute of img tags. Not changing `href` values of anchor elements is expected behavior. Going to close this issue as a result. 

Let us know if we can be of any more help!

**Comment by wladston** [comment]
I have a HUGE stack of changes almost ready to commit :) will issue a pull request soon, maybe it even fixes his issues! :+1:
