### ISSUE TITLE
Release 1.1.0 is empty

### ISSUE THREAD

**Issue by scarlac** [imgix/imgix-wordpress#17]
Your latest release with the much anticipated merge is actually a completely empty folder. You maaaay want to fix that ;)

![screen shot 2015-09-21 at 15 35 47](https://cloud.githubusercontent.com/assets/895369/9993224/e4d1c1d8-6076-11e5-8aed-97d813867cbf.png)

![screen shot 2015-09-21 at 15 35 54](https://cloud.githubusercontent.com/assets/895369/9993197/c2aa2e92-6076-11e5-811d-b9d3b2b27f71.png)

**Comment by wladston** [comment]
I can confirm that the zip file provided for release 1.1.0 is indeed empty.

**Comment by kellysutton** [comment]
Something must have gotten messed up in the release script. We'll take a look and fix the issue. Sorry for the trouble!

**Comment by kellysutton** [comment]
I've replaced the ZIP file for 1.1.0 on the releases. Marking this as closed.

**Comment by scarlac** [comment]
Thanks, Kelly :)
