### ISSUE TITLE
Imgix not processing image URLs but adding parameters

### ISSUE THREAD

**Issue by Glark** [imgix/imgix-wordpress#2]
Example in WP post:

`<img src="http://XXXXX.com/m/podcast-example.jpg" alt="" width="950" height="534" class="size-full wp-image-10" />`

Becomes (I have auto format checked in settings):

`<img src="http://XXXXX.com/m/podcast-example.jpg?auto=format" alt="" width="950" height="534" class="size-full wp-image-10">`

I believe it should do this, yes?

`<img src="http://XXXX.imgix.net/m/podcast-example.jpg?auto=format" alt="" width="950" height="534" class="size-full wp-image-10">`

**Comment by kellysutton** [comment]
This appears to be a bug. We will investigate. Thanks for bringing it to our attention!

**Comment by kellysutton** [comment]
@Glark We've pushed some fixes in the latest version (1.0.2) of the plugin.

Can you give that a try and see if it fixes your issue? https://github.com/imgix/imgix-wordpress/releases/tag/1.0.2

**Comment by Glark** [comment]
Updated to 1.0.2 but unfortunately there's no change in behavior.

**Comment by kellysutton** [comment]
Alright, can you create a WordPress project that exhibits this behavior and post the ZIP file somewhere? That will help us recreate and fix the issue.

**Comment by Glark** [comment]
Probably, what exactly are you looking for? I can easily backup this whole site for you via WP Engine's backup system. It's just one post and a handful of templates ATM. Theme? DB too?

**Comment by kellysutton** [comment]
Ideally, just the smallest possible WordPress installation that recreates the issue should suffice. Make sure you don't include any sensitive data.

**Comment by Glark** [comment]
Did you ever figure this one out? I saw the plugin was at 1.0.3 but still no joy on this end on the URL replacement bit of the script.

**Comment by kellysutton** [comment]
Hi @Glark,

We still have not been able to get to the bottom of what's causing this issue. Thank you for your continued patience.

**Comment by Glark** [comment]
No problem. I'm just doing some slow burn dev on the new site that is trying to use Imgix. If it would help to have WP admin access, I can provide. I'll just clone the project for you. Let me know if that's helpful.

**Comment by Glark** [comment]
Holy crap, I figured it out and I am not in any way a programmer. See if this makes sense:

I think the issue was you assumed images are in wp-content but we set them for the /m directory. I looked through do-functions.php and found wp-content references at line 104 which I just took out and now everything works.

Original:

    // img src tags
    $content = str_replace('src="'.home_url('/').'wp-content/', 'src="'.$slink.'wp-content/', $content);
    $content = str_replace('src=\''.home_url('/').'wp-content/', 'src=\''.$slink.'wp-content/', $content);
    // img href tags
    $content = str_replace('href="'.home_url('/').'wp-content/', 'href="'.$slink.'wp-content/', $content);
    $content = str_replace('href=\''.home_url('/').'wp-content/', 'href=\''.$slink.'wp-content/', $content);

Edited:

    // img src tags
    $content = str_replace('src="'.home_url('/').'', 'src="'.$slink.'', $content);
    $content = str_replace('src=\''.home_url('/').'', 'src=\''.$slink.'', $content);
    // img href tags
    $content = str_replace('href="'.home_url('/').'', 'href="'.$slink.'', $content);
    $content = str_replace('href=\''.home_url('/').'', 'href=\''.$slink.'', $content);

I'm sure there's a better way to remove the quotes that used to surround wp-content but that's above my pay grade.

**Comment by aryeharmon** [comment]
i am having the same issue and did not have that code in functions php

**Comment by wladston** [comment]
In the next version I'm pushing, this problem, and lots of others issues will be gone. I'll try to commit this today, hang on tight!

**Comment by aryeharmon** [comment]
is it already in the dev branch? i'd love to start using it

**Comment by kellysutton** [comment]
Sounds good, @wladston. I'll take a look and merge it in when it's ready.

**Comment by wladston** [comment]
@aryeharmon @kellysutton  I've been working on this in the last days, but haven't pushed it yet. I'm just doing a last code review before I push it.

**Comment by Glark** [comment]
Not functions.php, do-functions.php, in the plugin folder.

**Comment by wladston** [comment]
@Glark Can you check if you have any issues using this version? https://github.com/imgix/imgix-wordpress/pull/12 it seems to be working perfectly for me.

**Comment by wladston** [comment]
@aryeharmon I just pushed it! You can try using my patched version. It should fix this bug https://github.com/wladston/imgix-wordpress/commit/a6760a536a2f6f6dbf34d12ca04708249e0b90dc

**Comment by wladston** [comment]
@kellysutton pushed it. You can see that I made TONS of changes, let me know what you think.

**Comment by kellysutton** [comment]
Just merged in @wladston's work and released 1.1.0. Can you pull that down and let me know if that fixes your problems, @Glark?

**Comment by wladston** [comment]
Hey @kellysutton, thanks :) There are many other things that I wanted to add. I think the most important that could be done now is to integrate https://github.com/imgix/imgix-php. By doing this, the plugin gets support for signed images as a bonus :)

**Comment by Glark** [comment]
@kellysutton @wladston  This sounds awesome, I will try to update the plugin soon and I'll report back. Looking forward to giving it a spin.

**Comment by kellysutton** [comment]
Definitely. Might take a crack at that myself this weekend. I was also looking into using PHP's `DOMDocument` as part of the `'the_content'` hook for safer replacement of all of these URLs: http://php.net/manual/en/class.domdocument.php

**Comment by wladston** [comment]
yup, seems like a great idea! I'll keep on checking the activity :)

**Comment by Glark** [comment]
Finally reporting back. This solved my issues above. The featured image and sidebar images are not being processed but I just saw a ticket on that so I'll pick it up over there.

**Comment by kellysutton** [comment]
Awesome stuff. Closing!
