### ISSUE TITLE
Would be great to have the ability to define default parameters

### ISSUE THREAD

**Issue by mrdoinel** [imgix/imgix-wordpress#25]
In the Source options, there is a way to specify default params for example "or=0&lossless=1".
Those params are not added into WP images.

I was thinking that adding a text field in the plugin options so user can specify default params (i.e for copyright) would do the trick.
Then the value entered in the text field is added to default params in get_global_params_string function.

Let me know if this sound a good idea ?

**Comment by kellysutton** [comment]
HI @mrdoinel,

We actually recommend using default parameters for each Source, which can be configured in the web dashboard: https://webapp.imgix.com.

We won't be implementing this here for that reason. As such, I'm closing the issue. Thank you for your feedback!
