### ISSUE TITLE
Problem Installing Latest Release 1.0.2

### ISSUE THREAD

**Issue by alecdibble** [imgix/imgix-wordpress#7]
http://imgur.com/cO0q1qn

Wordpress Version 4.2.2

**Comment by kellysutton** [comment]
Hi @alecdibble,

You will need to unzip the ZIP file and move the `plugin/` folder into place manually. Let us know if you have any difficulties.

(If there's a better way to be packaging up this plugin, please open a Pull Request and we'll gladly review it. Thanks!)
